### ISSUE TITLE
Node v4 compatibility

### ISSUE THREAD

**Issue by brycekahle** [spark/node-aes-ccm#1]
@stemail23 What was the issue you saw installing this on node 4? I had no problems.

**Comment by stemail23** [comment]
Sorry, it seems that was a false alarm. I got a bunch of node-gyp errors, but when I tried again later it worked fine, so I deleted my original post. Should have given you the heads-up too!

Do you have any knowledge of when I might expect to see CCM support rolled into the main crypto library too?

Cheers

**Comment by brycekahle** [comment]
I don't have any idea on timeline, unfortunately.
